"""
JARVIS Security Subsystem (Batches 12, 13, 14, 15).
Authoritative entry point for PIN policy, secure storage, verification, sessions,
3-attempt lockout, security question recovery, and centralized policy engine.
"""

from jarvis.security.contracts import (
    AuthenticationStatus,
    AuthenticationResult,
    AuthenticationContext,
    PinCredential,
    AuthSession,
)
from jarvis.security.pin_policy import PinPolicy
from jarvis.security.pin_crypto import PINHasher
from jarvis.security.credential_store import PinCredentialStore
from jarvis.security.session_manager import SessionManager
from jarvis.security.rate_limit import AttemptTracker
from jarvis.security.lockout_models import LockoutStatus, LockoutReason, LockoutState
from jarvis.security.lockout_store import LockoutStore
from jarvis.security.lockout_manager import LockoutManager
from jarvis.security.recovery_models import (
    RecoveryStateEnum,
    SecurityQuestionCredential,
    RecoveryChallenge,
    RecoveryLockoutState,
)
from jarvis.security.recovery_crypto import RecoveryAnswerHasher, normalize_answer
from jarvis.security.recovery_store import RecoveryStore
from jarvis.security.recovery_service import RecoveryService, LockoutRecoveryService
from jarvis.security.auth_manager import AuthenticationManager
from jarvis.security.events import (
    AuthenticationSucceededEvent,
    AuthenticationFailedEvent,
    SessionCreatedEvent,
    SessionRevokedEvent,
    PinChangedEvent,
    PinAttemptFailedEvent,
    PinAttemptSucceededEvent,
    PinLockoutTriggeredEvent,
    PinAuthenticationBlockedEvent,
    SessionRevokedDueToLockoutEvent,
    SecurityQuestionEnrolledEvent,
    SecurityQuestionUpdatedEvent,
    SecurityRecoveryStartedEvent,
    SecurityRecoveryAnswerFailedEvent,
    SecurityRecoveryAnswerVerifiedEvent,
    SecurityRecoveryLockoutStartedEvent,
    SecurityPinResetCompletedEvent,
    SecurityRecoveryDeniedEvent,
)
from jarvis.security.policy import (
    PolicyEngine,
    ApprovalEngine,
    PolicyRepository,
    Principal,
    PrincipalType,
    RiskLevel,
    PolicyDecisionType,
    ApprovalStatus,
    CyberScopeCategory,
    AuthorizationRequest,
    PolicyDecision,
    ApprovalRequest,
    ScopedApproval,
    CyberAuthorizationContext,
    PolicyError,
    AuthorizationDeniedError,
    ApprovalError,
    ApprovalRequiredError,
    ApprovalNotFoundError,
    ApprovalExpiredError,
    ApprovalAlreadyConsumedError,
    ApprovalInvalidError,
    ScopeViolationError,
    DelegationError,
    PolicyConfigurationError,
    CyberAuthorizationError,
)

__all__ = [
    "AuthenticationStatus",
    "AuthenticationResult",
    "AuthenticationContext",
    "PinCredential",
    "AuthSession",
    "PinPolicy",
    "PINHasher",
    "PinCredentialStore",
    "SessionManager",
    "AttemptTracker",
    "LockoutStatus",
    "LockoutReason",
    "LockoutState",
    "LockoutStore",
    "LockoutManager",
    "RecoveryStateEnum",
    "SecurityQuestionCredential",
    "RecoveryChallenge",
    "RecoveryLockoutState",
    "RecoveryAnswerHasher",
    "normalize_answer",
    "RecoveryStore",
    "RecoveryService",
    "LockoutRecoveryService",
    "AuthenticationManager",
    "AuthenticationSucceededEvent",
    "AuthenticationFailedEvent",
    "SessionCreatedEvent",
    "SessionRevokedEvent",
    "PinChangedEvent",
    "PinAttemptFailedEvent",
    "PinAttemptSucceededEvent",
    "PinLockoutTriggeredEvent",
    "PinAuthenticationBlockedEvent",
    "SessionRevokedDueToLockoutEvent",
    "SecurityQuestionEnrolledEvent",
    "SecurityQuestionUpdatedEvent",
    "SecurityRecoveryStartedEvent",
    "SecurityRecoveryAnswerFailedEvent",
    "SecurityRecoveryAnswerVerifiedEvent",
    "SecurityRecoveryLockoutStartedEvent",
    "SecurityPinResetCompletedEvent",
    "SecurityRecoveryDeniedEvent",
    "PolicyEngine",
    "ApprovalEngine",
    "PolicyRepository",
    "Principal",
    "PrincipalType",
    "RiskLevel",
    "PolicyDecisionType",
    "ApprovalStatus",
    "CyberScopeCategory",
    "AuthorizationRequest",
    "PolicyDecision",
    "ApprovalRequest",
    "ScopedApproval",
    "CyberAuthorizationContext",
    "PolicyError",
    "AuthorizationDeniedError",
    "ApprovalError",
    "ApprovalRequiredError",
    "ApprovalNotFoundError",
    "ApprovalExpiredError",
    "ApprovalAlreadyConsumedError",
    "ApprovalInvalidError",
    "ScopeViolationError",
    "DelegationError",
    "PolicyConfigurationError",
    "CyberAuthorizationError",
]
